version: '3'

volumes:
  local_postgres_data: { }
  local_postgres_data_backups: { }

services:
  postgres:
    image: postgres:15
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - local_postgres_data:/var/lib/postgresql/data


  django: &django
    build:
      context: ./
      dockerfile: ./compose/local/django/Dockerfile
    image: base-default-api
    depends_on:
      - postgres
    volumes:
      - ./api:/app
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.db
      - ./.envs/.local/.cloud
    ports:
      - "8000:8000"
    command: /start

  redis:
    image: redis:6.2
