# Generated by Django 3.2 on 2025-01-10 17:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notebooks', '0003_auto_20241114_2324'),
    ]

    operations = [
        migrations.AddField(
            model_name='notebook',
            name='accelerator_type',
            field=models.IntegerField(choices=[(0, 'Accelerator Type Unspecified'), (2, 'Nvidia Tesla P100'), (3, 'Nvidia Tesla V100'), (4, 'Nvidia Tesla P4'), (5, 'Nvidia Tesla T4'), (11, 'Nvidia Tesla A100'), (12, 'Nvidia A100 80Gb'), (13, 'Nvidia L4'), (8, 'Nvidia Tesla T4 Vws'), (9, 'Nvidia Tesla P100 Vws'), (10, 'Nvidia Tesla P4 Vws')], default=0, null=True),
        ),
        migrations.AddField(
            model_name='notebook',
            name='boot_disk',
            field=models.IntegerField(blank=True, default=150, null=True, validators=[django.core.validators.MinValueValidator(150)]),
        ),
        migrations.AddField(
            model_name='notebook',
            name='core_count',
            field=models.PositiveIntegerField(default=1, null=True),
        ),
        migrations.AddField(
            model_name='notebook',
            name='data_disk',
            field=models.IntegerField(blank=True, default=50, null=True, validators=[django.core.validators.MinValueValidator(50)]),
        ),
    ]
