# Generated by Django 3.2 on 2024-09-04 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20240828_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='country',
            field=models.CharField(choices=[('Argentina', 'Argentina'), ('Bahamas', 'Bahamas'), ('Barbados', 'Barbados'), ('Belice', 'Belice'), ('Bolivia', 'Bolivia'), ('Brasil', 'Brasil'), ('Chile', 'Chile'), ('Colombia', 'Colombia'), ('Costa Rica', 'Costa Rica'), ('Cuba', 'Cuba'), ('Dominica', 'Dominica'), ('Ecuador', 'Ecuador'), ('El Salvador', 'El Salvador'), ('Granada', 'Granada'), ('Guatemala', 'Guatemala'), ('Guyana', 'Guyana'), ('Haití', 'Haití'), ('Honduras', 'Honduras'), ('Jamaica', 'Jamaica'), ('México', 'México'), ('Nicaragua', 'Nicaragua'), ('Panamá', 'Panamá'), ('Paraguay', 'Paraguay'), ('Perú', 'Perú'), ('Puerto Rico', 'Puerto Rico'), ('República Dominicana', 'República Dominicana'), ('San Cristóbal y Nieves', 'San Cristóbal y Nieves'), ('Santa Lucía', 'Santa Lucía'), ('San Vicente y las Granadinas', 'San Vicente y las Granadinas'), ('Surinam', 'Surinam'), ('Trinidad y Tobago', 'Trinidad y Tobago'), ('Uruguay', 'Uruguay'), ('Venezuela', 'Venezuela')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='industry',
            field=models.CharField(choices=[('Automotive', 'Automotive'), ('Technology', 'Technology'), ('Energy', 'Energy'), ('Chemical', 'Chemical'), ('Food', 'Food'), ('Pharmaceutical', 'Pharmaceutical'), ('Textile and Fashion', 'Textile and Fashion'), ('Construction', 'Construction'), ('Financial Services', 'Financial Services'), ('Tourism and Hospitality', 'Tourism and Hospitality'), ('Entertainment', 'Entertainment'), ('Mining', 'Mining'), ('Transportation and Logistics', 'Transportation and Logistics'), ('Shipbuilding', 'Shipbuilding'), ('Agriculture and Livestock', 'Agriculture and Livestock'), ('Healthcare and Biotechnology', 'Healthcare and Biotechnology'), ('Defense and Security', 'Defense and Security'), ('Professional Services', 'Professional Services')], max_length=255),
        ),
    ]
