# Generated by Django 3.2 on 2024-09-17 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20240904_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='country',
            field=models.CharField(blank=True, choices=[('Argentina', 'Argentina'), ('Bahamas', 'Bahamas'), ('Barbados', 'Barbados'), ('Belice', 'Belice'), ('Bolivia', 'Bolivia'), ('Brasil', 'Brasil'), ('Chile', 'Chile'), ('Colombia', 'Colombia'), ('Costa Rica', 'Costa Rica'), ('Cuba', 'Cuba'), ('Dominica', 'Dominica'), ('Ecuador', 'Ecuador'), ('El Salvador', 'El Salvador'), ('Granada', 'Granada'), ('Guatemala', 'Guatemala'), ('Guyana', 'Guyana'), ('Haití', 'Haití'), ('Honduras', 'Honduras'), ('Jamaica', 'Jamaica'), ('México', 'México'), ('Nicaragua', 'Nicaragua'), ('Panamá', 'Panamá'), ('Paraguay', 'Paraguay'), ('Perú', 'Perú'), ('Puerto Rico', 'Puerto Rico'), ('República Dominicana', 'República Dominicana'), ('San Cristóbal y Nieves', 'San Cristóbal y Nieves'), ('Santa Lucía', 'Santa Lucía'), ('San Vicente y las Granadinas', 'San Vicente y las Granadinas'), ('Surinam', 'Surinam'), ('Trinidad y Tobago', 'Trinidad y Tobago'), ('Uruguay', 'Uruguay'), ('Venezuela', 'Venezuela')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='organization',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
