# Generated by Django 3.2 on 2024-11-13 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_user_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='country',
            field=models.CharField(blank=True, choices=[('Argentina', 'Argentina'), ('Bahamas', 'Bahamas'), ('Barbados', 'Barbados'), ('Belize', 'Belize'), ('Bolivia', 'Bolivia'), ('Brazil', 'Brazil'), ('Chile', 'Chile'), ('Colombia', 'Colombia'), ('Costa Rica', 'Costa Rica'), ('Cuba', 'Cuba'), ('Dominica', 'Dominica'), ('Ecuador', 'Ecuador'), ('El Salvador', 'El Salvador'), ('Grenada', 'Grenada'), ('Guatemala', 'Guatemala'), ('Guyana', 'Guyana'), ('Haiti', 'Haiti'), ('Honduras', 'Honduras'), ('Jamaica', 'Jamaica'), ('Mexico', 'Mexico'), ('Nicaragua', 'Nicaragua'), ('Panama', 'Panama'), ('Paraguay', 'Paraguay'), ('Peru', 'Peru'), ('Puerto Rico', 'Puerto Rico'), ('Dominican Republic', 'Dominican Republic'), ('Saint Kitts and Nevis', 'Saint Kitts and Nevis'), ('Saint Lucia', 'Saint Lucia'), ('Saint Vincent and the Grenadines', 'Saint Vincent and the Grenadines'), ('Suriname', 'Suriname'), ('Trinidad and Tobago', 'Trinidad and Tobago'), ('Uruguay', 'Uruguay'), ('Venezuela', 'Venezuela')], max_length=255, null=True),
        ),
    ]
