#!/bin/sh

set -o errexit
set -o pipefail
set -o nounset

mkdir -p ./api/api/static

pwd
ls -lah

ls -lah /app

python manage.py collectstatic --noinput
python manage.py migrate

echo "Starting gunicorn!"
#gunicorn config.wsgi:application --bind 0.0.0.0:$PORT --workers 1

daphne config.asgi:application -b 0.0.0.0 -p 8000
