#!/bin/sh

set -o errexit
set -o pipefail
set -o nounset

python manage.py collectstatic --noinput
python manage.py migrate

crond

echo "Starting gunicorn!"
gunicorn config.wsgi:application --bind 0.0.0.0:$PORT --workers 1 --threads 8 --timeout 0

#daphne config.asgi:application -b 0.0.0.0 -p 8000
